### ISSUE TITLE
Unable to patch application: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by slaterin** [microsoftgraph/msgraph-sdk-go#111]
Hi, 

I've tried a few different ways to Patch an application, but I cannot get it to work. I'm a bit of a newbie to Go, so apologies if this is something I should've been able to spot. With the code below I am able to successfully retrieve the current Redirect URIs for my application, however I am then unable to Patch the same application. I'm wondering if it's something I'm not doing correctly, any help is very much appreciated.

I've did have a look at some of the previous issues and tried things like `go get -u` but I've had no luck.

Relevant code:
```go
	graphClient := msgraphsdk.NewGraphServiceClient(adapter)

	//Get application
	app, err := graphClient.ApplicationsById(appId).Get(nil)
	if err != nil {
		fmt.Printf("Problem with getting app: %v\n", err)
	}
	currentRedirectURIS := app.GetWeb().GetRedirectUris()
	fmt.Printf("Current URIs: %s\n", currentRedirectURIS)

	// Patch Application
	requestBody := graph.NewApplication()
	uris := graph.NewWebApplication()
	uris.SetRedirectUris([]string {
		"https://test-app.com",
	})

	requestBody.SetWeb(uris)
	patchOptions := &applications.ApplicationItemRequestBuilderPatchOptions {
		Body: requestBody,
	}
	graphClient.ApplicationsById(appId).Patch(patchOptions)
```

Output of a build:

```
Current URIs: [https://test-123.com]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x139b9d4]

goroutine 1 [running]:
github.com/microsoft/kiota/serialization/go/json.(*JsonSerializationWriter).WriteObjectValue(0xc00033d068, {0x1468e09, 0x3}, {0x0, 0x0})
        /Users/matt/go/pkg/mod/github.com/microsoft/kiota/serialization/go/json@v0.0.0-20220316090511-468a319ac5ba/json_serialization_writer.go:246 +0x34
github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph.(*Application).Serialize(0xc000390280, {0x1511120, 0xc00033d068})
        /Users/matt/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.14.0/models/microsoft/graph/application.go:816 +0xfd
github.com/microsoft/kiota/serialization/go/json.(*JsonSerializationWriter).WriteObjectValue(0xc00033d068, {0x0, 0x0}, {0x1502ff0, 0xc000390280})
        /Users/matt/go/pkg/mod/github.com/microsoft/kiota/serialization/go/json@v0.0.0-20220316090511-468a319ac5ba/json_serialization_writer.go:253 +0x1bf
github.com/microsoft/kiota/abstractions/go.(*RequestInformation).SetContentFromParsable(0xc00033a780, {0x150bc38, 0xc00019a280}, {0x146d402, 0x10}, {0xc000392070, 0x1478145, 0x1})
        /Users/matt/go/pkg/mod/github.com/microsoft/kiota/abstractions/go@v0.0.0-20220316090511-468a319ac5ba/request_information.go:169 +0x153
github.com/microsoftgraph/msgraph-sdk-go/applications/item.(*ApplicationItemRequestBuilder).CreatePatchRequestInformation(0xc000337980, 0xc00011bf38)
        /Users/matt/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.14.0/applications/item/application_item_request_builder.go:156 +0x1b7
github.com/microsoftgraph/msgraph-sdk-go/applications/item.(*ApplicationItemRequestBuilder).Patch(0xc000337980, 0x1478145)
        /Users/matt/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.14.0/applications/item/application_item_request_builder.go:253 +0x25
main.main()
        /Users/matt/workspace/go-projects/repy-url-updater/pkg/testing/main.go:53 +0x4a5

Process finished with the exit code 2
``` 

Let me know if there's anything else I can provide to help figure this out. Thanks!

**Comment by baywet** [comment]
Hi @slaterin 
Thanks for trying the Go SDK and for reaching out.
You most likely ran into a bug at this point.
I've authored [a pull request](https://github.com/microsoft/kiota/pull/1413) to address the issue.
Once it gets merge, we'll need to update the generated SDK (this repo), most likely by next Tuesday.

**Comment by msl8r** [comment]
Hi @baywet, awesome! I will keep an eye out. Thanks for the quick response 👍🏼

**Comment by slaterin** [comment]
Ah awesome! Thanks for the quick response @baywet. I’ll keep an eye on that PR, cheers.

**Comment by baywet** [comment]
Update: PR #112 is the generation PR that should address this issue once it's merged and released.
