### ISSUE TITLE
Error adding filter query param to applications request

### ISSUE THREAD

**Issue by aramase** [microsoftgraph/msgraph-sdk-go#20]
`AddQueryParameters` fails with the following error:

```bash
INFO[0000] Getting application with display name=azwi-e2e-app-b886 filter=startswith(displayName, 'azwi-e2e-app-b886') 
panic: reflect: NumField of non-struct type *applications.ApplicationsRequestBuilderGetQueryParameters

goroutine 1 [running]:
reflect.(*rtype).NumField(0x0)
        /usr/local/go/src/reflect/type.go:1015 +0x66
github.com/microsoft/kiota/abstractions/go.(*RequestInformation).AddQueryParameters(0xc0000bc720, {0x6b3c20, 0xc0001d70a0})
        /home/anramase/go/pkg/mod/github.com/microsoft/kiota/abstractions/go@v0.0.0-20211112084539-17ac73ffdc7c/request_information.go:201 +0x131
github.com/microsoftgraph/msgraph-beta-sdk-go/applications.(*ApplicationsRequestBuilder).CreateGetRequestInformation(0xc0004b4420, 0xc00011fcb8)
        /home/anramase/go/pkg/mod/github.com/microsoftgraph/msgraph-beta-sdk-go@v0.1.2/applications/applications_request_builder.go:97 +0x153
github.com/microsoftgraph/msgraph-beta-sdk-go/applications.(*ApplicationsRequestBuilder).Get(0xc0004b4420, 0x79f888)
        /home/anramase/go/pkg/mod/github.com/microsoftgraph/msgraph-beta-sdk-go@v0.1.2/applications/applications_request_builder.go:138 +0x33
github.com/aramase/graphsdk/pkg/cloud.(*AzureClient).GetApplication(0xc00018a700, {0x10, 0x733b72}, {0x72c380, 0x11})
        /home/anramase/go/src/github.com/aramase/graphsdk/pkg/cloud/graph.go:69 +0x225
main.main()
        /home/anramase/go/src/github.com/aramase/graphsdk/cmd/sample/main.go:32 +0x166
```

Follow up issue to #17
cc @baywet

**Comment by baywet** [comment]
Hi @aramase 
Thanks for reporting this! And sorry about that, it was a miss from my side when addressing #17 
I authored https://github.com/microsoft/kiota/pull/843 to address this issue.
Hopefully it'll get merged before the weekly generation tomorrow, otherwise I'll also kick a new generation.
