### ISSUE TITLE
Nil values on reflection since release 0.31

### ISSUE THREAD

**Issue by ratzrattillo** [microsoftgraph/msgraph-sdk-go#224]
After upgrading to release 0.31 i experience errors when accessing my Mail Inbox.

The following example code shopuld help to grasp the issue:

``` go
package main

import (
	"context"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota-authentication-azure-go"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	msgraphcore "github.com/microsoftgraph/msgraph-sdk-go-core"
	"github.com/microsoftgraph/msgraph-sdk-go/models"
	"github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

type sanitizedMail struct {
	from        string
	subject     string
	date        string
	body        string
	id          string
	attachments string
}

func printOdataError(err error) {
	switch err.(type) {
	case *odataerrors.ODataError:
		typed := err.(*odataerrors.ODataError)
		fmt.Printf("error: %s", typed.Error())
		if terr := typed.GetError(); terr != nil {
			fmt.Printf("code: %s", *terr.GetCode())
			fmt.Printf("msg: %s", *terr.GetMessage())
		}
	default:
		fmt.Printf("%T > error: %#v", err, err)
	}
}

func main() {
	tenantID := "abc"
	clientID := "def"

	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		TenantID: tenantID,
		ClientID: clientID,
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"Mail.ReadWrite", "Mail.ReadWrite.Shared"})
	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		fmt.Printf("Error creating adapter: %v\n", err)
		return
	}
	client := msgraphsdk.NewGraphServiceClient(adapter)

	allFolders, err := client.Me().MailFolders().Get()
	if err != nil {
		fmt.Printf("Error getting the folders: %v\n", err)
		printOdataError(err)
	}

	pageIterator, err := msgraphcore.NewPageIterator(allFolders, adapter, models.CreateMailFolderFromDiscriminatorValue)

	inboxFolderId := ""
	err = pageIterator.Iterate(func(pageItem interface{}) bool {
		folder := pageItem.(models.MailFolderable)
		fmt.Printf("%s\n", *folder.GetDisplayName())
		if *folder.GetDisplayName() == "MyInbox" {
			inboxFolderId = *folder.GetId()
			return false
		} else {
			// Return true to continue the iteration
			return true
		}
	})

	fmt.Printf("Posteingang FolderId: %s\n", inboxFolderId)

	inbox, err := client.Me().MailFoldersById(inboxFolderId).ChildFolders().Get()
	if err != nil {
		fmt.Printf("Error getting the messages: %v\n", err)
		printOdataError(err)
	}
	pageIterator2, err := msgraphcore.NewPageIterator(inbox, adapter, models.CreateMailFolderFromDiscriminatorValue)

	mailingListsFolderId := ""
	err = pageIterator2.Iterate(func(pageItem interface{}) bool {
		subfolder := pageItem.(models.MailFolderable)
		fmt.Printf("%s\n", *subfolder.GetDisplayName())
		if *subfolder.GetDisplayName() == "MySubfolder" {
			mailingListsFolderId = *subfolder.GetId()
			return false
		}
		// Return true to continue the iteration
		return true
	})

	result, err := client.Me().MailFoldersById(mailingListsFolderId).Messages().Get()
	if err != nil {
		fmt.Printf("Error getting the messages: %v\n", err)
		printOdataError(err)
	}

	pageIterator3, err := msgraphcore.NewPageIterator(result, adapter, models.CreateMessageFromDiscriminatorValue)

	var mail models.Messageable = nil
	err = pageIterator3.Iterate(func(pageItem interface{}) bool {
		message := pageItem.(models.Messageable)
		fmt.Printf("%s\n", *message.GetSubject())

		mail = message
		// Return true to continue the iteration
		return true
	})

	fmt.Printf("HasAttachments: %v\n", *mail.GetHasAttachments())
	fmt.Printf("MIME-Type: %s\n", mail.GetBody().GetContentType().String())
	fmt.Printf("Contents: %s\n", *mail.GetBody().GetContent())

	mo := sanitizedMail{}
	mo.from = *mail.GetSender().GetEmailAddress().GetAddress()
	mo.subject = *mail.GetSubject()
	mo.date = mail.GetReceivedDateTime().String()
	mo.body = *mail.GetBody().GetContent()
	mo.id = *mail.GetId()
	mo.attachments = ""

	fmt.Printf("Mail: %v\n", mo)

	fmt.Printf("Number of attachments: %d\n", len(mail.GetAttachments()))
}
```

I receive the follwoing error (of course with valid tenantId and clientId):

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CZM48BW6S to authenticate.
panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 1 [running]:
reflect.Value.IsNil(...)
        C:/Program Files/Go/src/reflect/value.go:1506
github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage({0x6a82e0?, 0xc000185140?})
        C:/Users/abc/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.26.2/page_iterator.go:205 +0x57b 
github.com/microsoftgraph/msgraph-sdk-go-core.NewPageIterator({0x6a82e0?, 0xc000185140?}, {0x7b0530, 0xc0000685a0}, 0x71fe38)
        C:/Users/abc/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.26.2/page_iterator.go:54 +0x49   
main.main()
        C:/Users/abc/GolandProjects/mailfeed/src/main.go:69 +0x546

Process finished with the exit code 2
```

What is the reason for this behaviour?

It would be helpful to have more examples also on how to write more elegant code with this SDK. Sometimes i feel like my code looks sluggish due to a lack of good resources...

**Comment by ratzrattillo** [comment]
Thank you for the information, but actually i went throug hthe whole 
authorization process. The error appears after successful login.

Am 21.07.2022 um 09:31 schrieb Ronald K:

**Comment by rkodev** [comment]
@ratzrattillo Yes, there was an issue that being addressed in this PR https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/105
