### ISSUE TITLE
Experiencing Page Iterator failure during MailFolder Iteration

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#249]
Possibly related to https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/105/
I am receiving the following error during iteration on MailFolders:
```go
   suite.go:77: test panicked: reflect: call of reflect.Value.IsNil on zero Value
            goroutine 59 [running]:
            runtime/debug.Stack()
                /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/debug/stack.go:24 +0x68
            github.com/stretchr/testify/suite.failOnPanic(0x14000276d00, {0x104fa3d60, 0x1400000e258})
                /Users/dadams39/go/pkg/mod/github.com/stretchr/testify@v1.8.0/suite/suite.go:77 +0x38
            github.com/stretchr/testify/suite.Run.func1.1()
                /Users/dadams39/go/pkg/mod/github.com/stretchr/testify@v1.8.0/suite/suite.go:161 +0x1f0
            panic({0x104fa3d60, 0x1400000e258})
                /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/panic.go:838 +0x204
            reflect.Value.IsNil(...)
                /opt/homebrew/Cellar/go/1.18/libexec/src/reflect/value.go:1506
            github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage({0x105a56440, 0x14000220300})
                /Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.27.0/page_iterator.go:203 +0x468
            github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator).next(0x140005116e0?)
                /Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.27.0/page_iterator.go:124 +0x38
            github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator).Iterate(0x140005116e0, 0x140005098c0?)
                /Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.27.0/page_iterator.go:90 +0x44
```

**Comment by dadams39** [comment]
The setup for receiving the error is textbook:

```go
response, err := gs.Client().Me().MailFolders().GetWithRequestConfigurationAndResponseHandler(options, nil)
...
pageIterator, err := msgraphgocore.NewPageIterator(
		response,
		Adapter(),
		models.CreateMailFolderFromDiscriminatorValue,
	)
	if err != nil {
		return nil, err
	}

	callbackFunc := func(entry any) bool {
		//switch category {
		//case messages:
		folder, ok := entry.(models.MailFolderable)
		if !ok {
			errs = support.WrapAndAppend(service.Adapter().GetBaseUrl(), errors.New("invalid return on HasFolder.mail iteration failure"), errs)
			return true
		}
		// Display name not set on folder
		if folder.GetDisplayName() == nil {
			return true
		}
		fmt.Printf("174 %s %s %v %v\n", category, folderName, folderID == nil, folder)
		name := *folder.GetDisplayName()
		fmt.Printf("Wrap: %s\n", *folder.GetId())
		if folderName == name {
			if folder.GetId() == nil {
				return true // invalid folder
			}
			folderID = folder.GetId()
		}
		/*
			case contacts:
				folder, ok := entry.(models.ContactFolder)
				if !ok {
					errs = support.WrapAndAppend(service.Adapter().GetBaseUrl(), errors.New("invalid return on HasFolder.contacts iteration failure"), errs)
					return true
				}
				// Display name not set on Contact Folder
				if folder.GetDisplayName() == nil {
					return true
				}
				if folderName == *folder.GetDisplayName() {
					folderID = folder.GetId()
				}
			default:
				return true
			}
		*/
		// Iterate iff folderID has not been populated
		return folderID == nil

	}

	if err := pageIterator.Iterate(callbackFunc); err != nil {

**Comment by baywet** [comment]
Hi @dadams39,
Thanks for reaching out and for using the Go SDK.
Can you confirm which version of the SDK and sdk core your application is using please?

**Comment by dadams39** [comment]
Certainly
```
github.com/microsoftgraph/msgraph-sdk-go v0.35.0
github.com/microsoftgraph/msgraph-sdk-go-core v0.27.0
```

**Comment by dadams39** [comment]
The ` github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage({0x105a56440, 0x14000220300})`
is one of the files that were changed in the [previous PR](https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/105/files)

**Comment by dadams39** [comment]
Nope... It is incorrect parsableFactory `models.CreateMailFolderFromDiscriminatorValue`--> `models.CreateMailFolderCollectionResponseFromDiscriminatorValue`

Can be closed. I forgot how terribly unhelpful that error is.
