### ISSUE TITLE
GetError panics with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bartek** [microsoftgraph/msgraph-sdk-go#434]
Hello!

Attempting to upgrade to `v0.56.0` but noticing a panic inside `odataerrors.ODataError`. Here's how we're using it (as part of a logging helper):

```go
	var odErr *odataerrors.ODataError
	if errors.As(err, &odErr) {
		if mErr := odErr.GetError(); mErr != nil {
			zapFields = append(zapFields,
				zap.Stringp("main_error", mErr.GetMessage()),
				zap.Stringp("main_error_code", mErr.GetCode()),
				zap.Stringp("main_error_target", mErr.GetTarget()),
			)
		}
	}   
```

The panic occurs on the line containing `odErr.GetError()`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x104aa767c]

goroutine 28 [running]:
testing.tRunner.func1.2({0x10678a000, 0x1088baa30})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1399 +0x378
panic({0x10678a000, 0x1088baa30})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x204
github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors.(*ODataError).GetError(0x1070c0520?)
	/Users/bartek/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.56.0/models/odataerrors/o_data_error.go:48 +0x1c
github.com/atolio/lumen/services/source_fleet/sources/azure/pkg/client.LogClientError(0x1400041f950?, {0x105ea2f63, 0x13}, {0x10728b180, 0x1400003d300}, {0x0, 0x0, 0x0})
```

Here's the culprit code inside the SDK:

```go
// GetError gets the error property value. The error property
func (m *ODataError) GetError()(MainErrorable) {
    val, err := m.GetBackingStore().Get("errorEscaped")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(MainErrorable)
    }
    return nil
}    
```

This is because `GetBackingStore()` returns a `nil`, while the .Get() method is being called on it.

I'm not familiar enough with what this backing store represents, so I'm not sure the best course of action. Is this a user error, or is it a genuine issue in the SDK?

Finally, I can confirm this panic does not occur in prior versions.

**Comment by rkodev** [comment]
Hi @bartek , Could you kindly share some more information on the source of the odata error struct? It looks like Odata error struct you are accessing was not constructed via the method `odataerrors.NewODataError`. This could be the reason the backing store object is nil at the time the method `GetError` is invoked.

It would be helpful to know what API call returned this error

**Comment by bartek** [comment]
@rkodev The source of this error is the GraphServiceClient, eg:

```
// client is of type msgraphsdk.GraphServiceclient
results, err := c.client.Subscriptions().Get(ctx, nil)
if err != nil {
  LogClientError(s.logger, "Failed to get subscription", err)
}
```

Based on this error, it's clear that the API is returning a `ODataError` type (as the errors.As `ok` check passes), but the zero value of this ODataError type does not seem usable.

I can't seem to copy an existing ODataError onto a new error created using the New function, as I run into another nil pointer dereference, e.g:

```
if errors.As(err, &odErr) {
   err := odataerrors.NewODataError()
   err.SetError(odErr.GetError()) 
   // etc...
}
```

This code is not suitable, of course, but I figured I'd try to get the appropriate initialize in place. Unfortunately calling `GetError` fails with the nil dereference, likely because the originating error from the GraphServiceClient is not correctly initializing the error?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x10504767c]

goroutine 25 [running]:
testing.tRunner.func1.2({0x106d2a000, 0x108e5aa30})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1399 +0x378
panic({0x106d2a000, 0x108e5aa30})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x204
github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors.(*ODataError).GetError(0x10782b180?)
	/Users/bartek/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.56.0/models/odataerrors/o_data_error.go:48 +0x1c
github.com/atolio/lumen/services/source_fleet/sources/azure/pkg/client.LogClientError(0x1400045e260?, {0x106442f83, 0x13}, {0x10782b180, 0x140002aa500}, {0x0, 0x0, 0x0})
	/Users/bartek/workspace/lumen/services/source_fleet/sources/azure/pkg/client/helpers.go:43 +0x220
github.com/atolio/lumen/services/source_fleet/sources/azure/pkg/export.(*exporter).ExportUsers(0x140002ab9c0, {0x107845918, 0x140002ab8c0}, {0x0?, 0x108ead680?, 0x10642c6b2?})
```

**Comment by bartek** [comment]
This looks to have been resolved.
