### ISSUE TITLE
panic while iterating over Page Item

### ISSUE THREAD

**Issue by vijayrajah** [microsoftgraph/msgraph-sdk-go#558]
i want to get a list of apps.

Here is my code
```
func getApPs(ctx context.Context) error {

	opts := applications.ApplicationsRequestBuilderGetRequestConfiguration{
		QueryParameters: &applications.ApplicationsRequestBuilderGetQueryParameters{
			Select: []string{"displayName", "appId", "id", "keyCredentials", "passwordCredentials"},
			Top:    to.Ptr[int32](100),
		},
	}

	resp, err := client.Applications().Get(ctx, &opts)
	if err != nil {
		printOdataError(err)
		return errors.Join(err, fmt.Errorf("unable to get list of Apps"))
	}

	pIter, err := msgraphgocore.NewPageIterator[*models.Application](resp, client.GetAdapter(), models.CreateApplicationFromDiscriminatorValue)
	if err != nil {
		return errors.Join(err, fmt.Errorf("unable to create iterator for app"))
	}

	cnt := 1
	err = pIter.Iterate(ctx,
		func(pageItem *models.Application) bool {
			fmt.Printf("ID: %s, name: %s, cnt: %d\n", *pageItem.GetAppId(), *pageItem.GetDisplayName(), cnt)
			cnt++
			return true
		},
	)

	fmt.Printf("there are %d apps", len(apps))

	return nil

}
```

This prints all the 100 App details & Panics.

```
panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 1 [running]:
reflect.Value.IsNil({0x0, 0x0, 0x0})
        C:/Users/<username>/go_1.21.0/src/reflect/value.go:1568 +0x172
github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage[...]({0x288ad60, 0xc001064130})
        C:/Users/<username>/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:219 +0xe5
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator[...]).next(0x29befe0, {0x29baa48, 0xc0001f07d0})
        C:/Users/<username>/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:136 +0x245
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator[...]).Iterate(0x29befe0, {0x29baa48, 0xc0001f07d0}, 0xc00034bc28)
        C:/Users/<username>/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:96 +0x174
main.getAPPs({0x29baa48, 0xc0001f07d0})
        C:/Users/<username>/GolandProjects/az-ad-principal-service/ad.go:43 +0x753
main.main()
        C:/Users/<username>/GolandProjects/az-ad-principal-service/main.go:127 +0x625
```

it seems I need to stop the execution of the loop. 

How do I do that? is there an example on how to do that ? (if I do not know how many Apps I have, like when getting all the apps in my org)

**Comment by philipf** [comment]
Hi @vijayrajah, I had a similar issue (https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/222) today and it turns out that an incorrect value for the constructor function for the factory parser for the `NewPageIterator` can result in this type of error.

I didn't test your scenario but a brief look at the source code leads me to believe that you should use `models.CreateApplicationCollectionResponseFromDiscriminatorValue()` instead

**Before**
```go
pIter, err := msgraphgocore.NewPageIterator[*models.Application](resp, client.GetAdapter(), models.CreateApplicationFromDiscriminatorValue)
```

**After**
```go
pIter, err := msgraphgocore.NewPageIterator[*models.Application](resp, client.GetAdapter(), models.CreateApplicationCollectionResponseFromDiscriminatorValue)
```

I am hoping that the SDK team can provide a fool-proof mechanism to ensure that the model and discriminator (factory func) cannot be out-of-sync, or at least provide an error message if this happens and supporting documentation to know which models and discriminators go together.

**Comment by vijayrajah** [comment]
@philipf -- Thanks for your time, on this. 

I tried to use this SDK, but I was having lot of issues mostly due to documentation & other issues (non-idiomatic code, poor dev exp.. )

I'm now using https://github.com/manicminer/hamilton

**Comment by philipf** [comment]
@vijayrajah it looks promising, I'll check it out

**Comment by eric-millin** [comment]
> Hi @vijayrajah, I had a similar issue ([microsoftgraph/msgraph-sdk-go-core#222](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/222)) today and it turns out that an incorrect value for the constructor function for the factory parser for the `NewPageIterator` can result in this type of error.
> 
> I didn't test your scenario but a brief look at the source code leads me to believe that you should use `models.CreateApplicationCollectionResponseFromDiscriminatorValue()` instead
> 
> **Before**
> 
> ```go
> pIter, err := msgraphgocore.NewPageIterator[*models.Application](resp, client.GetAdapter(), models.CreateApplicationFromDiscriminatorValue)
> ```
> 
> **After**
> 
> ```go
> pIter, err := msgraphgocore.NewPageIterator[*models.Application](resp, client.GetAdapter(), models.CreateApplicationCollectionResponseFromDiscriminatorValue)
> ```
> 
> I am hoping that the SDK team can provide a fool-proof mechanism to ensure that the model and discriminator (factory func) cannot be out-of-sync, or at least provide an error message if this happens and supporting documentation to know which models and discriminators go together.

I hit this panic several times. My solution was to write unit tests that return paginated responses to the client. Once I had one working, it was easy to repeat. Happy to share some examples, if you think it'd be helpful.

**Comment by rkodev** [comment]
Hi @vijayrajah ,

This issue should have been resolved by this [PR](https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/245). Please tes with library github.com/microsoftgraph/msgraph-sdk-go-core updated  to 1.0.2 and above
