### ISSUE TITLE
Error deserializing GET calendars response

### ISSUE THREAD

**Issue by janfreymann** [microsoftgraph/msgraph-sdk-go#73]
Hi, 
thanks for developing the Go SDK for Microsoft Graph. This is very helpful for me. Obtaining credentials via the device code login works fine, but once I request the list of calendars with `client.Me().Calendars().Get(nil)`, the following error occurs:

```
panic: interface conversion: interface {} is graph.OnlineMeetingProviderType, not *graph.OnlineMeetingProviderType

goroutine 1 [running]:
github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph.(*Calendar).GetFieldDeserializers.func1({0x101352ea0, 0x140001c6100}, {0x10136d158, 0x14000013290})
	/Users/jfreymann/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.8.0/models/microsoft/graph/calendar.go:209 +0x148
github.com/microsoft/kiota/serialization/go/json.(*JsonParseNode).GetObjectValue(0x140000134a0, 0x10135ae40)
	/Users/jfreymann/go/pkg/mod/github.com/microsoft/kiota/serialization/go/json@v0.0.0-20220125101815-87c13b40a6fb/json_parse_node.go:171 +0x2a4
github.com/microsoft/kiota/serialization/go/json.(*JsonParseNode).GetCollectionOfObjectValues(0x14000013e80, 0x10135ae40)
	/Users/jfreymann/go/pkg/mod/github.com/microsoft/kiota/serialization/go/json@v0.0.0-20220125101815-87c13b40a6fb/json_parse_node.go:196 +0x164
github.com/microsoftgraph/msgraph-sdk-go/me/calendars.(*CalendarsResponse).GetFieldDeserializers.func2({0x1013376c0, 0x1400018e600}, {0x10136d158, 0x14000013e80})
	/Users/jfreymann/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.8.0/me/calendars/calendars_response.go:62 +0x44
github.com/microsoft/kiota/serialization/go/json.(*JsonParseNode).GetObjectValue(0x14000013e90, 0x10135ae38)
	/Users/jfreymann/go/pkg/mod/github.com/microsoft/kiota/serialization/go/json@v0.0.0-20220125101815-87c13b40a6fb/json_parse_node.go:171 +0x2a4
github.com/microsoft/kiota/http/go/nethttp.(*NetHttpRequestAdapter).SendAsync(0x140000a81e0, {0x0, 0x0, 0x140000947b0, 0x140000947e0, {0x0, 0x0, 0x0}, 0x14000094720, {0x101263e73, ...}, ...}, ...)
	/Users/jfreymann/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20211203130928-8449c9e67101/nethttp_request_adapter.go:158 +0x15c
github.com/microsoftgraph/msgraph-sdk-go/me/calendars.(*CalendarsRequestBuilder).Get(0x14000094780, 0x0)
	/Users/jfreymann/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.8.0/me/calendars/calendars_request_builder.go:118 +0xac
main.main()
```

It seems like the deserializer for the response is not matching the actual JSON response. Could you please check if the generated code for the `/calendars` endpoint is correct?

Thanks and kind regards,

Jan Freymann

**Comment by baywet** [comment]
Hi @janfreymann 
Thanks for trying the SDK and thanks for reaching out.
This is an issue we've noticed yesterday and I already put together a [pull request in the generator to address it](https://github.com/microsoft/kiota/pull/1121/)
Once the pull request gets merged, the next weekly generation (usually happens on Tuesdays) will fix the issue, I'll revert here when this happens.

**Comment by janfreymann** [comment]
Great, thanks for the quick response!

**Comment by janfreymann** [comment]
Thank you very much! It is working now :)
