### ISSUE TITLE
Unable to query Groups fatal invalid memory address

### ISSUE THREAD

**Issue by eric-evangelista** [microsoftgraph/msgraph-sdk-go#74]
Thanks for the active support on this sdk. 
I've been trying to query the groups endpoint but getting a fatal error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10be594]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
	/usr/local/Cellar/go/1.17.3/libexec/src/io/io.go:633 +0xd4
io/ioutil.ReadAll(...)
	/usr/local/Cellar/go/1.17.3/libexec/src/io/ioutil/ioutil.go:27
github.com/microsoft/kiota/http/go/nethttp.(*CompressionHandler).Intercept(0xc00020e068, {0x16fa0a0, 0xc000208a50}, 0x15df740, 0xc000212300)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/compression_handler.go:69 +0x12a
github.com/microsoft/kiota/http/go/nethttp.(*middlewarePipeline).Next(0x8, 0x29005b8, 0x10)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:36 +0x52
github.com/microsoft/kiota/http/go/nethttp.RedirectHandler.Intercept({{0x1666710, 0x5}}, {0x16fa0a0, 0xc000208a50}, 0xc000062d80, 0xc000212300)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/redirect_handler.go:83 +0xb4
github.com/microsoft/kiota/http/go/nethttp.(*middlewarePipeline).Next(0x0, 0x0, 0x0)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:36 +0x52
github.com/microsoft/kiota/http/go/nethttp.RetryHandler.Intercept({{0x1666708, 0x0, 0x0}}, {0x16fa0a0, 0xc000208a50}, 0x104e934, 0xc000212300)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/retry_handler.go:99 +0xcb
github.com/microsoft/kiota/http/go/nethttp.(*middlewarePipeline).Next(0xc00021c500, 0x16f1600, 0x1)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:36 +0x52
github.com/microsoftgraph/msgraph-sdk-go-core.GraphODataQueryHandler.Intercept({0xc00021c500, {0x1666718}}, {0x16fa0a0, 0xc000208a50}, 0xf64feb8019465d01, 0xc000212300)
	/Users/user/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.0.7/graph_odata_query_handler.go:63 +0x1d4
github.com/microsoft/kiota/http/go/nethttp.(*middlewarePipeline).Next(0x1576de0, 0x0, 0xc00016f500)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:36 +0x52
github.com/microsoftgraph/msgraph-sdk-go-core.GraphTelemetryHandler.Intercept({{0xc000242000, 0x0}}, {0x16fa0a0, 0xc000208a50}, 0xc0004da580, 0xc000212300)
	/Users/user/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.0.7/graph_telemetry_handler.go:49 +0x209
github.com/microsoft/kiota/http/go/nethttp.(*middlewarePipeline).Next(0x0, 0x0, 0x0)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:36 +0x52
github.com/microsoft/kiota/http/go/nethttp.(*customTransport).RoundTrip(0x30, 0x16fa080)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/pipeline.go:44 +0x1e
net/http.send(0xc000212300, {0x16fa080, 0xc00020c068}, {0x1621a80, 0x1, 0x0})
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0x1c37900, 0xc000212300, {0x1643f61, 0xd, 0x0})
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x1c37900, 0xc000212300)
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/client.go:593
github.com/microsoft/kiota/http/go/nethttp.(*NetHttpRequestAdapter).getHttpResponseMessage(0xc00021a320, {0x0, 0x0, 0xc000208b40, 0xc000208b70, {0x0, 0x0, 0x0}, 0xc000208ae0, {0x16574d6, ...}, ...})
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/nethttp_request_adapter.go:100 +0x175
github.com/microsoft/kiota/http/go/nethttp.(*NetHttpRequestAdapter).SendAsync(0xc00021a320, {0x0, 0x0, 0xc000208b40, 0xc000208b70, {0x0, 0x0, 0x0}, 0xc000208ae0, {0x16574d6, ...}, ...}, ...)
	/Users/user/go/pkg/mod/github.com/microsoft/kiota/http/go/nethttp@v0.0.0-20220207185719-f6879aa1f3a7/nethttp_request_adapter.go:142 +0x78
github.com/microsoftgraph/msgraph-sdk-go/groups/item.(*GroupRequestBuilder).Get(0xc000208b10, 0x1652d7d)
	/Users/user/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.8.0/groups/item/group_request_builder.go:312 +0xbe
main.main()
	/Users/user/go/src/graph-api/main.go:59 +0x2bd
exit status 2
```

This is the code I'm trying out and it also happens to the commented `Me` endpoint. Not sure if I'm doing something wrong here. The dependencies seem to be all updated, and it seems like things go bad in the `result` line. Did some debugging and authentication piece gets the token, but it fails on the actual request.

```golang
package main

import (
	"context"
	"fmt"

	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota/authentication/go/azure"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

func main() {
	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		TenantID: "my-tenant-id",
		ClientID: "my-svc-principal-id",
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})
	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"Directory.Read.All"})
	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		fmt.Printf("Error creating adapter: %v\n", err)
		return
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	//result, err := client.Me().Get(nil)
	result, err := client.GroupsById("my-group-id").Get(nil)

	if err != nil {
		fmt.Printf("Error getting the group: %v\n", err)
	}

	fmt.Printf("Group detail: %v\n", result)
}
```

**Comment by baywet** [comment]
Hi @eric-evangelista,
Thanks for trying the SDK and for reaching out.
Can you make sure you're on the latest version of the components please by running `go get -u` at the root of your project please? (might take a few minutes)
Can you also share the JSON response of the REST request for the same group please? you can obfuscate the fields content if they contain sensitive data. You can use [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer#) to make the request.

Thanks for all that additional information.

**Comment by eric-evangelista** [comment]
Hi @baywet 
Thanks for looking into. Yesterday when I was testing it, I've run the `go get -u` into the project, but the error persisted.

Here is my the response from graph explorer:

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups/$entity",
    "id": "group-id",
    "deletedDateTime": null,
    "classification": null,
    "createdDateTime": "2022-01-19T01:56:08Z",
    "creationOptions": [],
    "description": "Just a group",
    "displayName": "myapp-members",
    "expirationDateTime": null,
    "groupTypes": [],
    "isAssignableToRole": null,
    "mail": null,
    "mailEnabled": false,
    "mailNickname": "abcdefg-01",
    "membershipRule": null,
    "membershipRuleProcessingState": null,
    "onPremisesDomainName": null,
    "onPremisesLastSyncDateTime": null,
    "onPremisesNetBiosName": null,
    "onPremisesSamAccountName": null,
    "onPremisesSecurityIdentifier": null,
    "onPremisesSyncEnabled": null,
    "preferredDataLocation": null,
    "preferredLanguage": null,
    "proxyAddresses": [],
    "renewedDateTime": "2022-01-19T01:56:08Z",
    "resourceBehaviorOptions": [],
    "resourceProvisioningOptions": [],
    "securityEnabled": true,
    "securityIdentifier": "S-1-12-1-0000000000-00000000-00000000-00000000",
    "theme": null,
    "visibility": null,
    "onPremisesProvisioningErrors": []
}
```

**Comment by eric-evangelista** [comment]
I've just done one more update on the project with `go get -u` and some packages were updated with today's releases. Testing once more produced the expected results and the app stopped crashing. Thanks!

Quick question: do you know why it takes so long to update the dependencies? I did in 2 different devices (Windows & macOS) at the same time, and both took around 30 minutes or so and they were mostly stuck at:
`go: downloading github.com/microsoft/kiota/http/go/nethttp`

**Comment by baywet** [comment]
That's great news! Closing (but we can keep discussing on the time aspect).

I'm not sure why it does that during the update but I've seen that behaviour too. To me it's strange that install + update the code to reference the new module + build only take a couple of seconds but upgrade takes 20/30 minutes sometimes.
What I have noticed is upgrading specific packages by hand (e.g. `go get -u github.com/microsoftgraph/msgraph-sdk-go`) is much faster than a blanket upgrade `go get -u`.
This leads me to think the blanket upgrade does much more work, and maybe repeats some work. It could be rebuilding multiple times the msgraph-sdk-go package and its sub-packages (which makes for a large number of packages) as it goes up the dependency tree. When you issue an update command for a specific package, it probably rebuilds only once.
To be clear, that's my guess, but I don't have any hard evidence at this point and I don't know enough about the inner works of the Go module resolution + compiler to make an opinion for sure.
Having somebody more experienced with Go take a look at that behaviour would be super helpful. At least to clarify whether this is an optimization issue in the Go package manager, something msgraph-sdk-go is doing wrong, or just "normal" because the package is large.

**Comment by eric-evangelista** [comment]
That's make sense. While we are at this, my approach will be to document the pain points on updates and try to do targeted ones and see what resolves what. Really appreciate your quick support @baywet good luck with the project!

**Comment by baywet** [comment]
Where would you document that? On the main readme?
You're most welcomed!

Cc @jasonjoh

**Comment by eric-evangelista** [comment]
Oh I meant document personal pain points in my project, so we can do operations faster on the scope of it. If I find anything worth sharing with the community I may as well send PR somewhere here or open an issue before so I can contribute.
